import React, { useEffect, useState } from 'react';
import { 
  Users, 
  Search, 
  Filter, 
  Download,
  Plus,
  Star,
  Mail,
  Phone,
  Calendar,
  MoreHorizontal,
  Loader2,
  ChevronRight,
  ArrowUpDown,
  MessageSquare
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { getLeads, Lead, updateLead, getConversations, Conversation } from '@/lib/api';
import { toast } from 'react-hot-toast';
import { format } from 'date-fns';

const statuses = ['New', 'Contacted', 'Qualified', 'Negotiation', 'Closed', 'Unqualified'];

export default function LeadPipeline() {
  const [leads, setLeads] = useState<Lead[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  const [sortConfig, setSortSortConfig] = useState({ key: 'score', direction: 'desc' });

  useEffect(() => {
    fetchLeads();
  }, []);

  const fetchLeads = async () => {
    try {
      const data = await getLeads();
      setLeads(data);
    } catch (error) {
      toast.error('Failed to load leads');
    } finally {
      setLoading(false);
    }
  };

  const handleStatusChange = async (id: string, newStatus: string) => {
    try {
      await updateLead(id, { status: newStatus });
      setLeads(prev => prev.map(l => l.id === id ? { ...l, status: newStatus } : l));
      toast.success(`Status updated to ${newStatus}`);
    } catch (error) {
      toast.error('Failed to update status');
    }
  };

  const exportToCSV = () => {
    if (leads.length === 0) return;
    
    const headers = ['Name', 'Telegram', 'Email', 'Phone', 'Score', 'Status', 'Interest', 'Date'];
    const rows = leads.map(l => [
      l.name,
      l.telegram_handle,
      l.email || '',
      l.phone || '',
      l.score,
      l.status,
      l.interest,
      format(new Date(l.created_at), 'yyyy-MM-dd')
    ]);

    const csvContent = [headers, ...rows].map(e => e.join(",")).join("\n");
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute("download", "voiceflow_leads.csv");
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    toast.success('Leads exported successfully');
  };

  const filteredLeads = leads
    .filter(l => {
      const matchesSearch = l.name.toLowerCase().includes(search.toLowerCase()) || 
                           l.telegram_handle.toLowerCase().includes(search.toLowerCase());
      const matchesStatus = statusFilter === 'all' || l.status === statusFilter;
      return matchesSearch && matchesStatus;
    })
    .sort((a: any, b: any) => {
      if (a[sortConfig.key] < b[sortConfig.key]) return sortConfig.direction === 'asc' ? -1 : 1;
      if (a[sortConfig.key] > b[sortConfig.key]) return sortConfig.direction === 'asc' ? 1 : -1;
      return 0;
    });

  const handleSort = (key: string) => {
    setSortSortConfig(prev => ({
      key,
      direction: prev.key === key && prev.direction === 'desc' ? 'asc' : 'desc'
    }));
  };

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h2 className="text-2xl font-bold">Lead Pipeline</h2>
          <p className="text-muted-foreground text-sm">Manage and qualify leads generated by VoiceFlow AI.</p>
        </div>
        <div className="flex gap-3 w-full md:w-auto">
          <button 
            onClick={exportToCSV}
            className="flex-1 md:flex-none px-4 py-2 border rounded-lg flex items-center justify-center gap-2 hover:bg-secondary/50 transition-colors text-sm font-medium"
          >
            <Download className="w-4 h-4" /> <span className="hidden sm:inline">Export CSV</span>
          </button>
          <button className="flex-1 md:flex-none px-4 py-2 bg-primary text-white rounded-lg flex items-center justify-center gap-2 hover:shadow-lg transition-all active:scale-95 text-sm font-medium">
            <Plus className="w-4 h-4" /> Add Lead
          </button>
        </div>
      </div>

      <div className="flex flex-col md:flex-row gap-4">
        <div className="flex-1 flex items-center gap-2 px-4 py-2 bg-card border rounded-lg shadow-sm focus-within:border-primary transition-all">
          <Search className="w-4 h-4 text-muted-foreground" />
          <input 
            type="text" 
            placeholder="Search leads..." 
            className="bg-transparent border-none outline-none text-sm w-full"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
        <div className="flex gap-2">
          <select 
            className="px-4 py-2 bg-card border rounded-lg text-sm outline-none focus:border-primary transition-all cursor-pointer"
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
          >
            <option value="all">All Statuses</option>
            {statuses.map(s => <option key={s} value={s}>{s}</option>)}
          </select>
          <button className="p-2 border rounded-lg hover:bg-secondary/50 transition-colors">
            <Filter className="w-4 h-4 text-muted-foreground" />
          </button>
        </div>
      </div>

      <div className="bg-card border rounded-xl shadow-sm overflow-hidden overflow-x-auto">
        {loading ? (
          <div className="p-20 flex items-center justify-center">
            <Loader2 className="w-8 h-8 text-primary animate-spin" />
          </div>
        ) : filteredLeads.length > 0 ? (
          <table className="w-full text-left min-w-[800px]">
            <thead>
              <tr className="bg-secondary/30 text-muted-foreground text-[10px] uppercase font-bold border-b tracking-widest">
                <th className="px-6 py-4 cursor-pointer hover:text-primary transition-colors" onClick={() => handleSort('name')}>
                  <div className="flex items-center gap-1">Lead <ArrowUpDown className="w-3 h-3" /></div>
                </th>
                <th className="px-6 py-4">Status</th>
                <th className="px-6 py-4 cursor-pointer hover:text-primary transition-colors" onClick={() => handleSort('score')}>
                  <div className="flex items-center gap-1">AI Score <ArrowUpDown className="w-3 h-3" /></div>
                </th>
                <th className="px-6 py-4">Interest</th>
                <th className="px-6 py-4">Created</th>
                <th className="px-6 py-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              {filteredLeads.map((lead) => (
                <tr key={lead.id} className="hover:bg-secondary/10 transition-colors group">
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-full bg-secondary flex items-center justify-center font-bold text-primary shrink-0">
                        {lead.name[0]}
                      </div>
                      <div>
                        <div className="font-semibold text-sm">{lead.name}</div>
                        <div className="text-xs text-muted-foreground">{lead.telegram_handle}</div>
                      </div>
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <select 
                      className={cn(
                        "px-3 py-1 rounded-full text-[10px] font-bold uppercase border bg-white outline-none cursor-pointer",
                        lead.status === 'Qualified' ? 'text-green-600 border-green-100' :
                        lead.status === 'Negotiation' ? 'text-blue-600 border-blue-100' :
                        lead.status === 'Unqualified' ? 'text-gray-500 border-gray-100' :
                        'text-amber-600 border-amber-100'
                      )}
                      value={lead.status}
                      onChange={(e) => handleStatusChange(lead.id, e.target.value)}
                    >
                      {statuses.map(s => <option key={s} value={s}>{s}</option>)}
                    </select>
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-2">
                      <div className="h-1.5 w-16 bg-secondary rounded-full overflow-hidden">
                        <div 
                          className={cn(
                            "h-full rounded-full",
                            lead.score > 70 ? "bg-primary" : lead.score > 30 ? "bg-amber-500" : "bg-gray-400"
                          )} 
                          style={{ width: `${lead.score}%` }} 
                        />
                      </div>
                      <span className="text-sm font-bold">{lead.score}</span>
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-1">
                      {[1, 2, 3].map((star) => (
                        <Star 
                          key={star} 
                          className={cn(
                            "w-4 h-4",
                            (lead.interest === 'High' || (lead.interest === 'Medium' && star <= 2) || (lead.interest === 'Low' && star <= 1)) 
                              ? "fill-amber-400 text-amber-400" 
                              : "text-gray-200"
                          )} 
                        />
                      ))}
                    </div>
                  </td>
                  <td className="px-6 py-4 text-xs text-muted-foreground">
                    {format(new Date(lead.created_at), 'MMM d, yyyy')}
                  </td>
                  <td className="px-6 py-4 text-right">
                    <div className="flex items-center justify-end gap-2">
                      <button className="p-2 hover:bg-secondary rounded-lg transition-colors border shadow-sm">
                        <Mail className="w-4 h-4 text-muted-foreground" />
                      </button>
                      <button className="p-2 hover:bg-secondary rounded-lg transition-colors border shadow-sm">
                        <MessageSquare className="w-4 h-4 text-muted-foreground" />
                      </button>
                      <button className="p-2 hover:bg-secondary rounded-lg transition-colors">
                        <MoreHorizontal className="w-4 h-4 text-muted-foreground" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        ) : (
          <div className="flex flex-col items-center justify-center p-20 text-center">
            <Users className="w-16 h-16 text-muted-foreground/20 mb-4" />
            <h3 className="font-bold text-lg">No leads found</h3>
            <p className="text-sm text-muted-foreground max-w-xs mx-auto">Either no conversations have reached the score threshold or your filters are too strict.</p>
          </div>
        )}
        <div className="px-6 py-4 bg-secondary/10 border-t flex items-center justify-between text-xs text-muted-foreground font-medium uppercase tracking-wider">
          <span>{filteredLeads.length} leads total</span>
          <div className="flex gap-2">
            <button className="px-3 py-1 border rounded-lg hover:bg-white disabled:opacity-50" disabled>Prev</button>
            <button className="px-3 py-1 border rounded-lg hover:bg-white disabled:opacity-50" disabled>Next</button>
          </div>
        </div>
      </div>
    </div>
  );
}
