import React from 'react';
import { 
  Users, 
  Search, 
  Filter, 
  Download,
  Plus,
  Star,
  Mail,
  Phone,
  Calendar,
  MoreHorizontal
} from 'lucide-react';
import { cn } from '@/lib/utils';

const mockLeads = [
  { id: 1, name: 'Alex Thompson', user: '@alex_dev', score: 85, status: 'Qualified', interest: 'High', lastActive: '2m ago' },
  { id: 2, name: 'Sarah Miller', user: '@sarah_m', score: 92, status: 'Negotiation', interest: 'High', lastActive: '15m ago' },
  { id: 3, name: 'Michael Chen', user: '@mike_c', score: 45, status: 'Contacted', interest: 'Medium', lastActive: '1h ago' },
  { id: 4, name: 'Emma Wilson', user: '@emma_w', score: 78, status: 'Qualified', interest: 'High', lastActive: '3h ago' },
  { id: 5, name: 'David Park', user: '@d_park', score: 12, status: 'Unqualified', interest: 'Low', lastActive: '1d ago' },
];

export default function LeadPipeline() {
  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold">Lead Pipeline</h2>
          <p className="text-muted-foreground text-sm">Manage and qualify leads generated by VoiceFlow AI.</p>
        </div>
        <div className="flex gap-3">
          <button className="px-4 py-2 border rounded-lg flex items-center gap-2 hover:bg-secondary/50 transition-colors text-sm font-medium">
            <Download className="w-4 h-4" /> Export
          </button>
          <button className="px-4 py-2 bg-primary text-white rounded-lg flex items-center gap-2 hover:shadow-lg transition-all active:scale-95 text-sm font-medium">
            <Plus className="w-4 h-4" /> Add Lead
          </button>
        </div>
      </div>

      <div className="flex gap-4">
        <div className="flex-1 flex items-center gap-2 px-4 py-2 bg-card border rounded-lg shadow-sm">
          <Search className="w-4 h-4 text-muted-foreground" />
          <input 
            type="text" 
            placeholder="Search leads by name or Telegram handle..." 
            className="bg-transparent border-none outline-none text-sm w-full"
          />
        </div>
        <button className="px-4 py-2 border rounded-lg flex items-center gap-2 hover:bg-secondary/50 transition-colors text-sm font-medium">
          <Filter className="w-4 h-4 text-muted-foreground" /> Filter
        </button>
      </div>

      <div className="bg-card border rounded-xl shadow-sm overflow-hidden">
        <table className="w-full text-left">
          <thead>
            <tr className="bg-secondary/30 text-muted-foreground text-xs uppercase font-bold border-b">
              <th className="px-6 py-4">Lead</th>
              <th className="px-6 py-4">Status</th>
              <th className="px-6 py-4">AI Score</th>
              <th className="px-6 py-4">Interest</th>
              <th className="px-6 py-4">Last Activity</th>
              <th className="px-6 py-4 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y">
            {mockLeads.map((lead) => (
              <tr key={lead.id} className="hover:bg-secondary/10 transition-colors">
                <td className="px-6 py-4">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-full bg-secondary flex items-center justify-center font-bold text-primary shrink-0">
                      {lead.name[0]}
                    </div>
                    <div>
                      <div className="font-semibold text-sm">{lead.name}</div>
                      <div className="text-xs text-muted-foreground">{lead.user}</div>
                    </div>
                  </div>
                </td>
                <td className="px-6 py-4">
                  <span className={cn(
                    "px-3 py-1 rounded-full text-[10px] font-bold uppercase border",
                    lead.status === 'Qualified' ? 'bg-green-50 text-green-600 border-green-100' :
                    lead.status === 'Negotiation' ? 'bg-blue-50 text-blue-600 border-blue-100' :
                    lead.status === 'Unqualified' ? 'bg-gray-50 text-gray-500 border-gray-100' :
                    'bg-amber-50 text-amber-600 border-amber-100'
                  )}>
                    {lead.status}
                  </span>
                </td>
                <td className="px-6 py-4">
                  <div className="flex items-center gap-2">
                    <div className="h-1.5 w-16 bg-secondary rounded-full overflow-hidden">
                      <div 
                        className={cn(
                          "h-full rounded-full",
                          lead.score > 70 ? "bg-primary" : lead.score > 30 ? "bg-amber-500" : "bg-gray-400"
                        )} 
                        style={{ width: `${lead.score}%` }} 
                      />
                    </div>
                    <span className="text-sm font-bold">{lead.score}</span>
                  </div>
                </td>
                <td className="px-6 py-4">
                  <div className="flex items-center gap-1">
                    {[1, 2, 3].map((star) => (
                      <Star 
                        key={star} 
                        className={cn(
                          "w-4 h-4",
                          (lead.interest === 'High' || (lead.interest === 'Medium' && star <= 2) || (lead.interest === 'Low' && star <= 1)) 
                            ? "fill-amber-400 text-amber-400" 
                            : "text-gray-200"
                        )} 
                      />
                    ))}
                  </div>
                </td>
                <td className="px-6 py-4 text-sm text-muted-foreground">
                  {lead.lastActive}
                </td>
                <td className="px-6 py-4 text-right">
                  <div className="flex items-center justify-end gap-2">
                    <button className="p-2 hover:bg-secondary rounded-lg transition-colors border shadow-sm">
                      <Mail className="w-4 h-4 text-muted-foreground" />
                    </button>
                    <button className="p-2 hover:bg-secondary rounded-lg transition-colors border shadow-sm">
                      <Phone className="w-4 h-4 text-muted-foreground" />
                    </button>
                    <button className="p-2 hover:bg-secondary rounded-lg transition-colors border shadow-sm">
                      <Calendar className="w-4 h-4 text-muted-foreground" />
                    </button>
                    <button className="p-2 hover:bg-secondary rounded-lg transition-colors">
                      <MoreHorizontal className="w-4 h-4 text-muted-foreground" />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        <div className="px-6 py-4 bg-secondary/10 border-t flex items-center justify-between text-sm text-muted-foreground">
          <span>Showing 5 of 452 hot leads</span>
          <div className="flex gap-2">
            <button className="px-3 py-1 border rounded-lg hover:bg-white disabled:opacity-50" disabled>Previous</button>
            <button className="px-3 py-1 border rounded-lg hover:bg-white">Next</button>
          </div>
        </div>
      </div>
    </div>
  );
}
